on:
  push:
    branches: [master]
name: Build a Front End Framework Website
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Build Project
      run: |
        npm install
        CI=false npm run-script build
